#!/bin/bash
# Codespaces起動時に環境を自動設定するスクリプト
# GitHub Secretsから環境変数を読み込み、SSH鍵を設定します

echo "🔧 AI AutoForm - 環境設定を開始..."

# =============================================================================
# 1. SSH鍵の設定（VPS接続用）
# =============================================================================
if [ -n "$THESIDE_VPS_SSH_PRIVATE_KEY" ]; then
    echo "📦 SSH鍵を設定中..."
    mkdir -p ~/.ssh
    echo "$THESIDE_VPS_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519_vps
    chmod 600 ~/.ssh/id_ed25519_vps
    
    # SSH config設定
    cat >> ~/.ssh/config << EOF

# TheSide AI AutoForm VPS
Host theside-vps
    HostName ${THESIDE_VPS_HOST:-153.126.154.158}
    User ${THESIDE_VPS_USER:-ubuntu}
    IdentityFile ~/.ssh/id_ed25519_vps
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF
    chmod 600 ~/.ssh/config
    echo "✅ SSH鍵設定完了（theside-vps でVPS接続可能）"
else
    echo "⚠️ THESIDE_VPS_SSH_PRIVATE_KEY が未設定です。VPS接続にはSSH鍵が必要です。"
fi

# =============================================================================
# 2. 環境変数の設定（.envファイル生成）
# =============================================================================
ENV_FILE="/workspaces/ai-auto-form/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "📦 .envファイルを生成中..."
    cat > "$ENV_FILE" << EOF
# TheSide AI AutoForm - Environment Variables
# Generated by postCreateCommand.sh on $(date)

# Flask Configuration
FLASK_APP=backend/app.py
FLASK_ENV=development
FLASK_DEBUG=True
PORT=5001
SECRET_KEY=${THESIDE_SECRET_KEY:-$(openssl rand -hex 32)}

# PostgreSQL Database Configuration
POSTGRES_DB=ai_autoform
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${THESIDE_POSTGRES_PASSWORD:-your_secure_password_here}
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

# Database URL
DATABASE_URL=postgresql://postgres:${THESIDE_POSTGRES_PASSWORD:-your_secure_password_here}@localhost:5432/ai_autoform

# Google Gemini API (for AI features)
GEMINI_API_KEY=${THESIDE_GEMINI_API_KEY:-your-gemini-api-key-here}

# VPS Configuration
VPS_HOST=${THESIDE_VPS_HOST:-153.126.154.158}
VPS_USER=${THESIDE_VPS_USER:-ubuntu}

# CORS Configuration
CORS_ORIGINS=http://localhost:8000,http://localhost:5001,https://*.app.github.dev

# Playwright Configuration
PLAYWRIGHT_HEADLESS=False
PLAYWRIGHT_BROWSER=webkit
EOF
    echo "✅ .envファイル生成完了"
else
    echo "ℹ️ .envファイルは既に存在します"
fi

# =============================================================================
# 3. Python依存関係のインストール
# =============================================================================
if [ -f "/workspaces/ai-auto-form/requirements.txt" ]; then
    echo "📦 Python依存関係をインストール中..."
    pip install -r /workspaces/ai-auto-form/requirements.txt --quiet
    echo "✅ Python依存関係インストール完了"
fi

# =============================================================================
# 4. Playwrightブラウザのインストール
# =============================================================================
echo "📦 Playwrightブラウザをインストール中..."
playwright install webkit --with-deps 2>/dev/null || echo "ℹ️ Playwrightインストールはスキップされました"

# =============================================================================
# 5. VPSの.envファイルを更新（GEMINI_API_KEY等）
# =============================================================================
if [ -n "$THESIDE_VPS_SSH_PRIVATE_KEY" ] && [ -n "$THESIDE_GEMINI_API_KEY" ]; then
    echo "📦 VPSの.envファイルを更新中..."
    
    # VPSの既存.envを更新（GEMINI_API_KEYを置換または追加）
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null theside-vps << 'REMOTE_SCRIPT'
cd /opt/ai-auto-form

# 既存のGEMINI_API_KEY行を削除して新しい値を追加
if [ -f .env ]; then
    grep -v "^GEMINI_API_KEY=" .env > .env.tmp || true
    mv .env.tmp .env
fi

# 新しいGEMINI_API_KEYを追加
echo "GEMINI_API_KEY=${THESIDE_GEMINI_API_KEY}" >> .env

echo "✅ VPSの.envを更新しました"
REMOTE_SCRIPT

    # 環境変数を直接渡してVPSの.envを更新
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null theside-vps "cd /opt/ai-auto-form && grep -v '^GEMINI_API_KEY=' .env > .env.tmp 2>/dev/null || touch .env.tmp; echo 'GEMINI_API_KEY=$THESIDE_GEMINI_API_KEY' >> .env.tmp; mv .env.tmp .env && echo '✅ VPSのGEMINI_API_KEY更新完了'"
    
    echo "✅ VPS環境変数の同期完了"
else
    echo "⚠️ VPS同期スキップ（SSH鍵またはGEMINI_API_KEYが未設定）"
fi

# =============================================================================
# 6. 完了メッセージ
# =============================================================================
echo ""
echo "🎉 TheSide AI AutoForm - 環境設定が完了しました！"
echo ""
echo "📋 次のステップ:"
echo "  1. docker compose up -d  # PostgreSQL起動"
echo "  2. python -m flask run --host=0.0.0.0 --port=5001  # Flask起動"
echo "  3. python -m http.server 8000  # HTMLサーバー起動"
echo ""
echo "🔗 VPS接続: ssh theside-vps"
echo ""
